default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: password

development:
  <<: *default
  database: carmax_development

test:
  <<: *default
  database: carmax_test

production:
  <<: *default
  database: carmax_production
  password: <%= ENV['CARMAX_DATABASE_PASSWORD'] %>
